import hljs from 'highlight.js/lib/core'
import python from 'highlight.js/lib/languages/python'
import javascript from 'highlight.js/lib/languages/javascript'
import typescript from 'highlight.js/lib/languages/typescript'
import xml from 'highlight.js/lib/languages/xml'  // html/xml
import json from 'highlight.js/lib/languages/json'
import cpp from 'highlight.js/lib/languages/cpp'
import java from 'highlight.js/lib/languages/java'
import bash from 'highlight.js/lib/languages/bash'

import {
  NButton,
  NInput,
  NForm,
  NFormItem,
  NSelect,
  NTable,
  NDataTable,
  NSpace,
  NCard,
  NSpin,
  NTag,
  NPagination,
  NModal,
  NDrawer,
  NMenu,
  NLayout,
  NLayoutHeader,
  NLayoutSider,
  NLayoutContent,
  NLayoutFooter,
  NIcon,
  NBreadcrumb,
  NBreadcrumbItem,
  NMessageProvider,
  NDialogProvider,
  NNotificationProvider,
  NLoadingBarProvider,
  NThing,
  NDivider,
  NEmpty,
  NResult,
  NDropdown,
  NAvatar,
  NPopover,
  NTooltip,
  NAlert,
  NUpload,
  NProgress,
  NStatistic,
  NGrid,
  NGridItem,
  // Typography
  NH1,
  NH2,
  NH3,
  NH4,
  NH5,
  NH6,
  NText,
  NP,
  NBlockquote,
  // Other missing components
  NBadge,
  NConfigProvider,
  NSwitch,
  NInputNumber,
  NCheckbox,
  NRadio,
  NRadioGroup,
  NRadioButton,
  NSlider,
  NRate,
  NTimePicker,
  NDatePicker,
  NColorPicker,
  NTab,
  NTabs,
  NTabPane,
  NStep,
  NSteps,
  NCollapse,
  NCollapseItem,
  NTimeline,
  NTimelineItem,
  NDescriptions,
  NDescriptionsItem,
  NList,
  NListItem,
  NScrollbar,
  NImage,
  NImageGroup,
  NNumberAnimation,
  NGradientText,
  NCode,
  NLi,
  NUl,
  NOl,
  NEllipsis,
  NInputGroup,
  NInputGroupLabel,
} from 'naive-ui'

hljs.registerLanguage('python', python)
hljs.registerLanguage('python3', python)
hljs.registerLanguage('javascript', javascript)
hljs.registerLanguage('typescript', typescript)
hljs.registerLanguage('html', xml)
hljs.registerLanguage('xml', xml)
hljs.registerLanguage('json', json)
hljs.registerLanguage('cpp', cpp)
hljs.registerLanguage('java', java)
hljs.registerLanguage('bash', bash)
hljs.registerLanguage('shell', bash)

export default defineNuxtPlugin((nuxtApp) => {
  const components = [
    NButton,
    NInput,
    NForm,
    NFormItem,
    NSelect,
    NTable,
    NDataTable,
    NSpace,
    NCard,
    NSpin,
    NTag,
    NPagination,
    NModal,
    NDrawer,
    NMenu,
    NLayout,
    NLayoutHeader,
    NLayoutSider,
    NLayoutContent,
    NLayoutFooter,
    NIcon,
    NBreadcrumb,
    NBreadcrumbItem,
    NMessageProvider,
    NDialogProvider,
    NNotificationProvider,
    NLoadingBarProvider,
    NThing,
    NDivider,
    NEmpty,
    NResult,
    NDropdown,
    NAvatar,
    NPopover,
    NTooltip,
    NAlert,
    NUpload,
    NProgress,
    NStatistic,
    NGrid,
    NGridItem,
    // Typography
    NH1,
    NH2,
    NH3,
    NH4,
    NH5,
    NH6,
    NText,
    NP,
    NBlockquote,
    // Other missing components
    NBadge,
    NConfigProvider,
    NSwitch,
    NInputNumber,
    NCheckbox,
    NRadio,
    NRadioGroup,
    NRadioButton,
    NSlider,
    NRate,
    NTimePicker,
    NDatePicker,
    NColorPicker,
    NTab,
    NTabs,
    NTabPane,
    NStep,
    NSteps,
    NCollapse,
    NCollapseItem,
    NTimeline,
    NTimelineItem,
    NDescriptions,
    NDescriptionsItem,
    NList,
    NListItem,
    NScrollbar,
    NImage,
    NImageGroup,
    NNumberAnimation,
    NGradientText,
    NCode,
    NLi,
    NUl,
    NOl,
    NEllipsis,
    NInputGroup,
    NInputGroupLabel,
  ].filter(Boolean) // 过滤不存在的组件
  // Naive UI 组件的 .name 属性是不带 N 前缀的（如 NInput.name === 'Input'），
  // 但模板中使用 <NInput>，所以需要加上 'N' 前缀才能正确注册。
  components.forEach(c => nuxtApp.vueApp.component('N' + c.name, c))
})
